// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(DojoContext))]
    partial class DojoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.FilaTreino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcaoDistracao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Nada/Andar")
                        .HasColumnName("acao_distracao");

                    b.Property<string>("AcaoPrincipal")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pulo Frente")
                        .HasColumnName("acao_principal");

                    b.Property<bool>("Concluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("concluido");

                    b.Property<DateTime>("DataProgramada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_programada");

                    b.Property<int>("NivelId")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_id");

                    b.Property<int>("OrdemFila")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ordem_fila");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrdemFila"));

                    b.Property<Guid>("RespostaId")
                        .HasColumnType("uuid")
                        .HasColumnName("resposta_id");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Neutro")
                        .HasColumnName("situacao");

                    b.Property<int>("TentativasFalhas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tentativas_falhas");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RespostaId");

                    b.ToTable("fila_treino_diario", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Fundamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("fundamentos", (string)null);
                });

            modelBuilder.Entity("Backend.Models.HistoricoTreino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_conclusao");

                    b.Property<Guid>("FundamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("fundamento_id");

                    b.Property<int>("NivelInt")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_int");

                    b.Property<string>("Personagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("personagem");

                    b.Property<Guid>("RespostaId")
                        .HasColumnType("uuid")
                        .HasColumnName("resposta_id");

                    b.Property<int>("SegundosRestantes")
                        .HasColumnType("integer")
                        .HasColumnName("segundos_restantes");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RespostaId");

                    b.ToTable("historico_treino", (string)null);
                });

            modelBuilder.Entity("Backend.Models.NivelStack", b =>
                {
                    b.Property<int>("Nivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Nivel"));

                    b.Property<string>("DescricaoSetup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao_setup");

                    b.Property<int>("SlotsDistracao")
                        .HasColumnType("integer")
                        .HasColumnName("slots_distracao");

                    b.Property<int>("SlotsFoco")
                        .HasColumnType("integer")
                        .HasColumnName("slots_foco!");

                    b.HasKey("Nivel");

                    b.ToTable("configuracao_niveis", (string)null);
                });

            modelBuilder.Entity("Backend.Models.RespostaTreino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Distracao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Foco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Jogo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LimiteDerrotas")
                        .HasColumnType("integer");

                    b.Property<int>("NivelDisciplina")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Personagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("respostas_treino", (string)null);
                });

            modelBuilder.Entity("Backend.Models.FilaTreino", b =>
                {
                    b.HasOne("Backend.Models.RespostaTreino", "Resposta")
                        .WithMany()
                        .HasForeignKey("RespostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resposta");
                });

            modelBuilder.Entity("Backend.Models.HistoricoTreino", b =>
                {
                    b.HasOne("Backend.Models.RespostaTreino", "Resposta")
                        .WithMany()
                        .HasForeignKey("RespostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resposta");
                });
#pragma warning restore 612, 618
        }
    }
}
